/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Globos;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.event.ActionEvent;
import java.util.Random;
import java.util.concurrent.Delayed;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ebelm
 */
public class GlobosFrame extends javax.swing.JFrame implements Runnable{
    /**
     * Creates new form GlobosFrame
     */
    Random azar = new Random();
    public GlobosFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(Color.black);
        area.setBackground(Color.white);
        inicializacion();
        btnParar.setVisible(false);
 
    }
    public Thread t;    
    public int incx=5;
    public int incy=5;
    public Globo[] globos=new Globo[10];
    public Globo globo_0;
    public Globo globo_1;
    public void inicializacion(){
    for(int i=0;i<globos.length;i++){
    globos[i]=new Globo(azar.nextInt(400), azar.nextInt(300), azar.nextInt(60),azar.nextInt(50), azar.nextInt(30),azar.nextInt(255),azar.nextInt(255),azar.nextInt(255));     
    globos[i].setXmax(area.getWidth());
    globos[i].setYmax(area.getHeight());
    }
    globo_0=new Globo(azar.nextInt(400), azar.nextInt(300), azar.nextInt(60), incx , incy, azar.nextInt(255),azar.nextInt(255),azar.nextInt(255));
    globo_1=new Globo(azar.nextInt(400), azar.nextInt(300), azar.nextInt(60), incx , incy, azar.nextInt(255),azar.nextInt(255),azar.nextInt(255));
    globo_0.setXmax(area.getWidth());
    globo_0.setYmax(area.getHeight());
    globo_1.setXmax(area.getWidth());
    globo_1.setYmax(area.getHeight());
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPoligonos = new javax.swing.JButton();
        area = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnAutomatico = new javax.swing.JButton();
        btnParar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        btnPoligonos.setText("POLIGONOS");
        btnPoligonos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPoligonosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout areaLayout = new javax.swing.GroupLayout(area);
        area.setLayout(areaLayout);
        areaLayout.setHorizontalGroup(
            areaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 755, Short.MAX_VALUE)
        );
        areaLayout.setVerticalGroup(
            areaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );

        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnBorrar.setText("BORRAR");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        btnAutomatico.setText("AUTOMATICO");
        btnAutomatico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAutomaticoActionPerformed(evt);
            }
        });

        btnParar.setText("PARAR");
        btnParar.setName(""); // NOI18N
        btnParar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPararActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(area, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btnPoligonos)
                        .addGap(54, 54, 54)
                        .addComponent(btnBorrar)
                        .addGap(78, 78, 78)
                        .addComponent(btnAutomatico, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(81, 81, 81)
                        .addComponent(btnParar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(35, 35, 35))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(area, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnParar)
                    .addComponent(btnAutomatico)
                    .addComponent(btnBorrar)
                    .addComponent(btnPoligonos)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

public void mostrar(Globo g){
g.Mostrar(area.getGraphics());
}
public void mostrar(Globo[] g){
for(int i=0;i<g.length;i++)
    g[i].Mostrar(area.getGraphics());
}
public void mover(Globo g){
g.Mover();
}
public void mover(Globo[] g){
for(int i=0;i<g.length;i++)
    g[i].Mover();
}

public void chocarpared(Globo g){
g.ChoqueConPared();
}
public void chocarpared(Globo[] g){
for(int i=0;i<g.length;i++)
    g[i].ChoqueConPared();
}
public void borrar(){
    Graphics g=area.getGraphics();
    g.setColor(Color.white);
    g.fillRect(0, 0, area.getWidth(),area.getHeight());
    g.setColor(Color.red);
    g.drawRect(0, 0,area.getWidth(),area.getHeight());
    
}
    private void btnPoligonosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPoligonosActionPerformed
    
    borrar();
    this.mostrar(globo_0);
    this.mostrar(globo_1);
    this.mostrar(globos);
     
    this.chocarpared(globo_0);
    this.chocarpared(globo_1);
    this.chocarpared(globos);
    
   globo_0.choqueConGlobos(globo_1);
   for(int i=0;i<globos.length;i++){
    globo_0.choqueConGlobos(globos[i]);
    globo_1.choqueConGlobos(globos[i]);
    for(int j=i+1;j<globos.length;j++)
        globos[i].choqueConGlobos(globos[j]); 
}   
   
    this.mover(globo_0);
    this.mover(globo_1);
    this.mover(globos);    
    }//GEN-LAST:event_btnPoligonosActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
    borrar();
    inicializacion();
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnAutomaticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAutomaticoActionPerformed
        t= new Thread(this);
        t.start();
        btnParar.setVisible(true);
        btnAutomatico.setVisible(false);
        btnBorrar.setVisible(false);
    }//GEN-LAST:event_btnAutomaticoActionPerformed

    private void btnPararActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPararActionPerformed
    t.stop();
    borrar();
    inicializacion();
    btnAutomatico.setVisible(true);
    btnParar.setVisible(false);
    btnBorrar.setVisible(true);
    }//GEN-LAST:event_btnPararActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GlobosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GlobosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GlobosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GlobosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GlobosFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel area;
    private javax.swing.JButton btnAutomatico;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnParar;
    private javax.swing.JButton btnPoligonos;
    private javax.swing.JButton jButton2;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        while(true){
        ActionEvent evt = null;
        btnPoligonosActionPerformed(evt);
        try {
            Thread.sleep(100);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    }


}
